Implements default settings for database connections (Issue #3)/Creates a URI based off the defaults
datajoint/datajoint-core pull request #12
Opened 2021-09-25 01:18 UTC by jonathanschroeter

For issue #3 
Creates default settings for the database connection (mysql or Postgress) and uses these to create a URI

- ConnectionSettings currently does not provide a username, password, and database_name yet (Leaves those defaults as blank just as settings.py does) (uri is currently: "mysql://:@localhost:3306/" because these are blank)
- createuri() creates a uri for either MySql or Postgres (currently the default is set to MySql, so that will be the one returned)

2021-09-27 15:25 UTC, jackson-nestelroad requested changes

2021-09-27 15:25 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +        if urimaker.database_type == DatabaseType::MySql {
Why not combine these two branches since they are doing the same thing? Just set the protocol (postgres or mysql) based on database_type so you only call format once.

2021-09-27 15:25 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +        }else if urimaker.database_type == DatabaseType::Postgres {
Space after bracket.

2021-09-27 15:25 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +    fn uri() -> String{
Space after "String"

2021-09-27 15:25 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +            uri = format!("mysql://{}:{}@{}:{}/{}",urimaker.username,urimaker.password,urimaker.hostname,urimaker.port.to_string(),urimaker.database_name);
What if username and/or password is empty? Will this be handled in a later PR? If so, leave a TODO comment.

2021-09-27 15:25 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +    fn uri() -> String{
This function doesn't make sense. It should be a method on a `ConnectionSettings` instance that returns the URI for the given settings. So first parameter should be `&self` and use those attributes. It shouldn't create a new object (`urimaker`).

2021-09-27 15:25 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +        println!("{}", uri);
I would remove this. We can print it before connecting if we want.

2021-09-27 23:37 UTC, jonathanschroeter commented on packages/datajoint-core/src/connection/settings.rs
> +        if urimaker.database_type == DatabaseType::MySql {
I see what you are getting at. Went with the idea of "protocol" being originally set to "mysql" and then would check if it was Postgress. Now format is only happening once. 
```rust
 let protocol = "mysql".to_string();
 if self.database_type == DatabaseType::Postgres {
       let protocol = "postgres".to_string();
  }
uri = format!("{}://{}:{}@{}:{}/{}",protocol,self.username,self.password,self.hostname,self.port.to_string(),self.database_name);
```

Is this better?

2021-09-27 23:39 UTC, jonathanschroeter commented on packages/datajoint-core/src/connection/settings.rs
> +    fn uri() -> String{
Code should now reflect this suggest change. 

```ruby
 fn uri(&self) -> String {
        //Hardcode in the username, password, and databasename, ect whatever is needed since those are not defaults
        let mut uri = "".to_string();
        //set the default protcall to mysql
        let protocol = "mysql".to_string();
        if self.database_type == DatabaseType::Postgres {
            let protocol = "postgres".to_string();
        }
        uri = format!("{}://{}:{}@{}:{}/{}",protocol,self.username,self.password,self.hostname,self.port.to_string(),self.database_name);
        return uri;
    }
```

Let me know if this is not what you are meaning.

2021-09-27 23:41 UTC, jonathanschroeter commented on packages/datajoint-core/src/connection/settings.rs
> +            uri = format!("mysql://{}:{}@{}:{}/{}",urimaker.username,urimaker.password,urimaker.hostname,urimaker.port.to_string(),urimaker.database_name);
Left it as a "TODO" at the top of the PR comment. If this is not the right place to put it, let me know.

2021-09-29 01:17 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +            let protocol = "postgres".to_string();
This is just using variable shadowing, so it won't actually reassign protocol, right?

2021-09-29 01:17 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +        //set the default protcall to mysql
Nit: space after //, capitalize first letter, and period at end. Same for above comment and typo.

2021-09-29 01:17 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +    fn uri(&self) -> String {
pub fn, same for above so it can be created outside.

2021-09-29 01:17 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +        let mut uri = "".to_string();
No longer needed? Are you able to just return the result of `format!()`?

2021-09-29 02:00 UTC, jackson-nestelroad approved these changes
LGTM.

2021-10-01 21:22 UTC, guzman-raphael approved these changes
@jonathanschroeter Thanks for the contribution! :handshake: 

Only small note I'd say here is about the line length (we usually limit it to `94` characters to make it easier on reviews on smaller screens such as mobile phones and 14" PC's). However, not high priority at the moment.

2021-10-01 21:22 UTC, merged