Adding SSL/TLS to URI connection string
datajoint/datajoint-core pull request #57
Opened 2021-10-18 21:30 UTC by jonathanschroeter

Not sure if this is how it is done, plus I wasn't sure how to test it. Wanted to put it up as a draft so people could review it to see if anyone had any other ideas. Was kind of hard to find information on URI connection strings.

Changes Made:
- Changed from use_tls to Option<bool> since having a none in the uri would break it (What do y'all think?)
- Created new variable that is either tls or ssl depending on if it is a mysql or postgres
- Changed the uri to house tls/ssl now

Found information from

- [First answer here](https://stackoverflow.com/questions/22301722/ssl-for-postgresql-connection-nodejs)
- [Uri from the Example Collector Definition](https://troubleshoot.sh/docs/collect/mysql/)

2021-10-18 23:00 UTC, jackson-nestelroad requested changes
Looking good! Just a few minor things to make the code cleaner :)

2021-10-18 23:00 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +        match self.use_tls {
This could be simplified, since you're doing a lot of the same thing twice...

The `postgres://user:pass@host:port/database` portion is always constructed reagardless of `self.use_tls`. Can you make it so `self.use_tls` is used just to append the last option (or not).

- Create URI with all common options (username, password, hostname, port, database_name)
- Check `self.use_tls`. If none, done. If a boolean value, add SSL/TLS flag with appropriate value.

2021-10-19 00:14 UTC, JHocevar commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +        &mut *this
I might move the null check (and ones below) to the top level of the function for less nesting and increased clarity.

2021-10-19 01:35 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +-Option<bool> is not FFI safe. Also forces us to return Some(false) for None
Here's an idea if you like it:
add `enum OptionalBool` in the `util` submodule. Make it a primitive enum (just like our others in datajoint-core, look at `DataJointType` for an example) and give it three options: True, False, None. Use this enum as the return value of the getter and the value for the setter. Do the appropriate conversion for Rust in these functions...

2021-10-19 02:04 UTC, JHocevar commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +-Option<bool> is not FFI safe. Also forces us to return Some(false) for None
I like this solution the most as well. Any other solution without the enum seems to have some kind of issue.

2021-10-19 04:28 UTC, jonathanschroeter commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +-Option<bool> is not FFI safe. Also forces us to return Some(false) for None
I made the change. The enum is being used for the return type of the getter, but one issue still remains. OptionalBool only has None, True, and False. Therefore, what should we return when the ConnectionSettings pointer is null? Right now I am returning OptionalBool::None, but we won't be able to tell if connection.use_tls is actually none or if the ConnectionSettings pointer is null

2021-10-19 04:34 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +-Option<bool> is not FFI safe. Also forces us to return Some(false) for None
I think this is OK, we do the same for some other getters (like get_database_type). The null check is really just for our library's own safety. It's the caller's fault if they use nullptr there.

2021-10-19 04:35 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +        // Problem is we won't be able to tell if this is null or is use_tls is actually None with this return
Remove comment, this is OK behavior.

2021-10-19 04:36 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +        None => return OptionalBool::None,
nit: Unneeded return statements

2021-10-19 04:36 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/util/boolenum.rs
> +/// Generalized types supported by DataJoint.
Change doc comment to describe what this is for?

2021-10-19 04:37 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/util/mod.rs
> +pub mod boolenum;
Remove pub here, unneeded.

2021-10-19 04:37 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +        //getting warnings about these variables never being read before being overwritten, not sure how to avoid it here
Remove this comment.

2021-10-19 04:38 UTC, jackson-nestelroad commented on packages/datajoint-core/src/connection/settings.rs
> +            None => return uri,
nit: Unneeded return statement

2021-10-19 04:39 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/connection/settings.rs
> +use crate::util::boolenum::OptionalBool;
can just use `crate::util::OptionalBool` since you used `pub use` in the util submodule.

2021-10-19 20:40 UTC, merged