File structure
datajoint/datajoint-core pull request #7
Opened 2021-09-16 21:29 UTC by JHocevar

2021-09-17 03:11 UTC, Rhijke commented
@JHocevar can you change the name of the PR to 'Create file structure with crates and connection submodule (Issue #1)' so it's easier to track later?

2021-09-17 20:49 UTC, jackson-nestelroad submitted a review, later dismissed
LGTM. A lot of this code will likely be replaced by actual library code, but file structure and everything interconnecting is great.

2021-09-18 15:05 UTC, guzman-raphael approved these changes
@JHocevar Nice job on your first PR! :handshake:
Only have some minor suggestions regarding styling and docs.

2021-09-18 15:06 UTC, guzman-raphael requested changes
Whoops, sorry. Submitted the review too early.

2021-09-18 18:53 UTC, JHocevar commented on datajoint-python/connection.py
> +    """)
Thanks for the link to the guidelines. I went back and forth a few ways on that one, and couldn't decide which format looked best.

2021-09-20 15:40 UTC, guzman-raphael approved these changes
@JHocevar Thanks for the updates! :rocket:

2021-09-20 15:40 UTC, merged