Added connection template to filestructure
datajoint/datajoint-core pull request #8
Opened 2021-09-22 18:46 UTC by JHocevar

Updates file structure with template connection module.
* Most of the code comes from @Rhijke 's [fork](https://github.com/Rhijke/datajoint-core)
* Updated python module and test file to look more like [datajoint-python](https://github.com/datajoint/datajoint-python)
* Added cargo workspace to build cargo modules from root
* Python connection module will look for compiled rust library in /target/debug/corelib

2021-09-22 20:09 UTC, jackson-nestelroad commented on datajoint-python/datajoint/connection.py
> +class ConnectionS(Structure):
Probably should make this name slightly more detailed (ConnectionStruct) if it has to be included like this.

2021-09-22 20:09 UTC, jackson-nestelroad commented on datajoint-python/datajoint/connection.py
> +lib.connection_free.argtypes = (POINTER(ConnectionS), )
Extra comma?

2021-09-22 20:20 UTC, JHocevar commented on datajoint-python/datajoint/connection.py
> +lib.connection_free.argtypes = (POINTER(ConnectionS), )
Trailing comma is python notation to create a tuple of 1 item, and the argtypes property needs a tuple.

2021-09-22 20:25 UTC, JHocevar commented on datajoint-python/datajoint/connection.py
> +class ConnectionS(Structure):
I agree, I'll update it to ConnectionStruct for now, and we can discuss cleaner options later.

2021-09-22 21:36 UTC, JHocevar commented on packages/datajoint-core/src/connection/mod.rs
> +    pub fn connect(&mut self, host: &str, user: &str, password: &str, reset: bool , use_tls: bool) {
Agreed, updated

2021-09-22 21:36 UTC, JHocevar commented on packages/datajoint-core/src/connection/mod.rs
> +    pub fn query(&self, query: &str) -> u32 {
agreed, updated

2021-09-22 22:05 UTC, Rhijke submitted a review, later dismissed

2021-09-23 20:29 UTC, jackson-nestelroad requested changes

2021-09-23 20:29 UTC, jackson-nestelroad commented on packages/datajoint-core-ffi-c/src/lib.rs
> +pub extern "C" fn connection_query(
Should also name this to raw_query to match the Rust function name.

2021-09-23 22:02 UTC, JHocevar commented on packages/datajoint-core-ffi-c/src/lib.rs
> +pub extern "C" fn connection_query(
fixed

2021-09-28 17:57 UTC, guzman-raphael requested changes
@JHocevar Thanks for the PR and nice work! :muscle: 

Nice you've gone through the trouble of accessing `cffi` vs `ctypes` in Python, looks like we can perhaps close this one in favor of #11. Seems like that `cffi` is the best way to go since it reduces the burden of declaration since we can reuse the `cbindgen` generated header.

2021-09-28 22:22 UTC, closed without merging