Fixing rare occurrence of when host_name is empty
datajoint/datajoint-core pull request #99
Opened 2021-11-04 03:26 UTC by jonathanschroeter

This is an extreme edge case, and will only be used if the user decides to set host_name as an empty string for some reason. Since our port is a u16, meaning it will never be empty, we will always need some sort of host_name to connect to MySQL or Postgres successfully. 

Was originally going to have it return an error code, but from what I saw those needed to be returned as i32, and the uri() function does not return that. Because of this, I did not see the need to mess with how the function works, and thought this could be an sufficient solution since it is a rare/harmless occurrence.

2021-11-04 03:31 UTC, jonathanschroeter commented
Another possible solution is instead of actually changing self.host_name in this function, we could just add "localhost" to the uri if we see self.host_name is empty.

2021-11-05 01:12 UTC, jackson-nestelroad commented
Yeah, I probably agree that changing it in place doesn't make a lot of sense. We should either return an Error or just put localhost in the string itself without changing the value in the object. Basically, make self immutable again.

2021-11-08 19:46 UTC, jackson-nestelroad requested changes
A lot of your comments in the code are triple-slash, but they should be double slash. Triple slash is for docs only (above functions). Double slash is for all code comments.

2021-11-09 02:51 UTC, Rhijke submitted a review, later dismissed

2021-11-11 16:04 UTC, jackson-nestelroad approved these changes

2021-11-11 16:04 UTC, merged